### PR TITLE
Metatag Issue #110 alternative: Return element without using #attached.

### LINKED ISSUE #110: Process '#attached' key in metatag data before adding tags to the head
Backdrop's version of metatag is different from D7's version in one important way: B's version **directly** adds the head tags in `metatag_preprocess_page()`.  This creates serious problems for metatag data that make use of the `#attached` key.

One example of that is the data provided by "Canonical URL" metatag in class `BackdropLinkMetaTag`. The data returned by `getElement` in this class looks a bit like this:
```php
$element['#attached'] = array(
  'backdrop_add_http_header' => array(
    0 => array(
      'Link', 
      '<' . $value . '>;' . backdrop_http_header_attributes(array('rel' => $element['#attributes']['rel'])), 
      TRUE
    ),
  )
);
```
This data fails to have any effect when it's run without any preprocessing through `backdrop_add_html_head($data, $tag);` in `metatag_preprocess_page()`.  The result of doing it this way (i.e. ADDING the data to the head BEFORE running the `#attached` function) is that, in this case, the Canonical URL `Link` header is never sent to the browser, as reported in #109.

There are TONS of other metatags, provided by a module I'm porting called `schema_metatag`, that make use of the `[#attached]` key. Because of the current approach taken by Backdrop (i.e. using  a "shortcut" and adding the tags directly in `metatag_preprocess_page()`, instead of doing it the way D7 does it),  those tags fail to be added, and in fact crash the rest of the tags added later, because they result in malformed `<meta>` tags being added.

There is a solution that avoids completely rewriting `metatag_preprocess_page()`. The solution is to check if the metatag data contains `[#attached]` as the top-most element. If it does, instead of directly adding the "raw" data, you call `backdrop_render()` for that data. Backdrop is smart enough to call the attached function with the arguments provided in the data, AND adds the tag to the head without the need of manually using `backdrop_add_html_head()`.

This solution solves not only the Canonical URL problem, but also all the `schema_metatag` malfunctioning tags.

I'll provide the PR later tonight. It's a one-liner.

### PR DESCRIPTION
**Pull request by quicksketch**
Fixes https://github.com/backdrop-contrib/metatag/issues/110.

An alternative approach to have schema_metatag return an element that uses the current Backdrop Metatag module approach to adding data. More information in that issue. I am reusing the Metatag issue to keep the conversation in one place rather than starting an additional thread in the schema_metatag queue.

### CODE REVIEW

File: src/SchemaNameBase.php [hunk 1]
```diff
@@ -142,9 +141,7 @@ public function getElement(array $options = array()) {
         'content' => static::outputValue($value),
       ],
     ];
-    return array(
-      '#attached' => array('backdrop_add_html_head' => array(array($element, $id))),
-    );
+    return $element;
```
Comment (quicksketch) [inline src/SchemaNameBase.php:144]: In my testing, if you needed to add an HTTP header in addition to the HTML, you could do the following:

```
      $element['#attached']['backdrop_add_http_header'][] = array('X-My-Tag', static::outputValue($value)), TRUE);
```

But if you only need to add an HTML tag, there's no need to use `#attached` or `backdrop_add_html_head` at all.

Comment (argiepiano) [reply src/SchemaNameBase.php:144]: Excellent! Thanks for checking. I've tested, and it works well without the need for `#attached`.  Merging...
